# Generated by Django 3.1.2 on 2020-10-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerEntry',
        ),
    ]
